version: '3'
services:
  mongodb:
    image: mongo:latest
    container_name: 'mongodb'

    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
      - MONGO_INITDB_DATABASE=admin
    volumes:
      - ./datadir:/data/db
    ports:
      - '27017:27017'
